# Fonts
font_family      JetBrainsMono Nerd Font
font_size        12

# Appearance
background_opacity 0.9
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
confirm_os_window_close 0

# Add search to kitty
map ctrl+shift+f launch --type=overlay --stdin-source=@screen_scrollback fzf --no-sort --no-mouse --exact -i

# Theme
include theme.conf
